# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'native-weex' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'WeexSDK'
  pod 'SDWebImage'
  pod 'WXDevtool', '0.24.0', :configurations => ['Debug']
  
end
